#ifndef __DEFINE_STATE_H__
#define __DEFINE_STATE_H__

#define WIDTH 17
#define HEIGHT 17

#define GBOARD_ORIGIN_X 30
#define GBOARD_ORIGIN_Y 6

#define STATE_EMPTY 0
#define STATE_ITEM_BOMB_MAX 111
#define STATE_ITEM_BOMB_RANGE 222
#define STATE_ITEM_CHARACTER_MOVE 333
#define STATE_ITEM_EXIST 20
#define STATE_BOMB_SETTING 400
#define STATE_BOMB_BOOM 444
#define STATE_NPC_WARNING 777
#define STATE_BOX 1
#define STATE_WALL 999

#define PLAYER 500
#define NPC1 501
#define NPC2 502
#define NPC3 503
#define NPC_EXIST 499

#define STATE_ITEM_CHARACTER_MOVE_REVERSE 969

#define SKY_BOMB_DROP_WARNING 416
#define WHO_SET_SKY_BOMB 610

#endif